### ISSUE TITLE
Stylish Org-Bullets for headings

### ISSUE THREAD

**Issue by santiyounger** [ryanpcmcquen/obsidian-org-mode#2]
I'd highly recommend taking a look at [spacemacs](https://www.spacemacs.org/) shortcuts and also stylistic look.

this is what headings look like in spacemacs from this project which can also be used in vanilla emacs 
[sabof/org-bullets: utf-8 bullets for org-mode](https://github.com/sabof/org-bullets)
![image](https://user-images.githubusercontent.com/51902730/118193372-2e579b80-b40d-11eb-868f-c7e7cdf33dd2.png)

I created a simple css snippet to replicate this look in Obsidian. However it's meant to read the heading from `#` markdown rather than `*` from org-mode.

This is what Obsidian looks like with my css hack

![image](https://user-images.githubusercontent.com/51902730/118193345-24359d00-b40d-11eb-8caa-e745c3f9fe48.png)

I'd love to know if this is something that could be added to your plugin. It'd be much better to have this as a plugin option
( rather than a hacky css snippet, which is the limits of my skill level)

Appreciate your time, this would be amazing

**Comment by ryanpcmcquen** [comment]
Yes, if you are willing to put the effort in (and already have CSS that accomplishes this), I would accept a PR adding it. It _should_ just be a matter of changing the selectors.

I don't have time to implement this myself. Whatever you do add, just **make sure that it works across all themes**.

**Comment by santiyounger** [comment]
Thanks for considering it. I totally get you.
 I'm not a programmer however I do know CSS. Do you think it's possible to figure it out purely based on CSS?
 Or do you recommend I learns some JS or typescript in order to achieve this?

Thanks!

**Comment by ryanpcmcquen** [comment]
Should be possible with pure CSS, just add to: [styles.css](https://github.com/ryanpcmcquen/obsidian-org-mode/blob/master/styles.css)

**Comment by santiyounger** [comment]
perfect thanks for the tip @ryanpcmcquen appreciate it!

**Comment by ryanpcmcquen** [comment]
@santiyounger have you tried adding some CSS?

**Comment by santiyounger** [comment]
> @santiyounger have you tried adding some CSS?

Hey sorry, I haven't tried it yet

**Comment by ryanpcmcquen** [comment]
@santiyounger, if you want to paste the CSS here, I can test it.

**Comment by santiyounger** [comment]
Thanks @ryanpcmcquen here's the version I've created. It isn't perfect, but works pretty good as a css snippet

Slight variations of it as well as a preview mode version are in the repo I created
https://github.com/santiyounger/Org-sidian-Bullets

Thanks a lot!

```css
/* org-sidian bullets heading symbol change */
/* colored bullets */
/* updated */
/* 2020-11-05 09:46 */

.CodeMirror-code > :not(.CodeMirror-activeline) .cm-formatting-header {
    display:none;
}
/* heading 1 */
.CodeMirror-code> :not(.CodeMirror-activeline) .cm-formatting-header+.cm-header-1::before,
.CodeMirror-code> :not(.CodeMirror-activeline) .cm-header-1:first-child::before {
    margin-right: 8px;
    color: #f8c537;
    content: "◉";
}
/* heading 2 */
.CodeMirror-code> :not(.CodeMirror-activeline) .cm-formatting-header+.cm-header-2::before,
.CodeMirror-code> :not(.CodeMirror-activeline) .cm-header-1:first-child::before {
    margin-left: 10px;
    margin-right: 8px;
    content: "○";
    color: #ff3333;
}
/* heading 3 */
.CodeMirror-code> :not(.CodeMirror-activeline) .cm-formatting-header+.cm-header-3::before,
.CodeMirror-code> :not(.CodeMirror-activeline) .cm-header-1:first-child::before {
    margin-left: 20px;
    margin-right: 8px;
    content: "✸";
    color: #f8c537;
}
/* heading 4 */
.CodeMirror-code> :not(.CodeMirror-activeline) .cm-formatting-header+.cm-header-4::before,
.CodeMirror-code> :not(.CodeMirror-activeline) .cm-header-1:first-child::before {
    margin-left: 30px;
    margin-right: 8px;
    content: "◉";
    color: #ff3333;
}
/* heading 5 */
.CodeMirror-code> :not(.CodeMirror-activeline) .cm-formatting-header+.cm-header-5::before,
.CodeMirror-code> :not(.CodeMirror-activeline) .cm-header-1:first-child::before {
    margin-left: 40px;
    margin-right: 8px;
    content: "○";
    color: #f8c537;
}
/* heading 6 */
.CodeMirror-code> :not(.CodeMirror-activeline) .cm-formatting-header+.cm-header-6::before,
.CodeMirror-code> :not(.CodeMirror-activeline) .cm-header-1:first-child::before {
    margin-left: 50px;
    margin-right: 8px;
    content: "✸";
    color: #ff3333;
}
```
